/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalPages;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author HP
 */
public class generatedailylogs extends javax.swing.JInternalFrame {

    /**
     * Creates new form generatedailylogs
     */
    public generatedailylogs() {
        initComponents();
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Rico Mambo", "19", "Male", "119778", "0912345678", "2:00PM", "3:00PM"},
                {"Shiela Galing", "24", "Female ", "117654", "09765432190", "10:00AM", "12:00PM"},
                {"Lady BarbEQ", "20", "Female", "145673", "09345267183", "10:30AM", "11:37 PM"},
                {"Adelia Danae", "19", "Female", "199675", "097505576134", "1:30PM", "4:00PM"},
                {"Jhosua Villarico", "25", "Male", "11768", "09675432710", "4:00PM", "4:50 PM"},
                {"Faith Servano", "21", "Female", "112657", "09765891267", "3:20PM", "4:00PM"},
                {"Ruth Lapure", "27", "Female", "15653", "09765889956", "9:00AM", "11:00AM"},
                {"Norman Mcgil", "18", "Male", "17654", "09778965477", "10:00AM", "11:55AM"}
            },
            new String [] {
                "Student Name", "Age", "Gender", "ID", "Contact No.", "Time In", "Time Out"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 610, 290);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("LIBRARY REPORT LIST");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 390, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
